### ISSUE TITLE
Setuptools only installs a working package when using the develop command.

### ISSUE THREAD

**Issue by FilBot3** [FilBot3/pypackgen#1]
# Problem
When working on Windows with Python 3.7 and setuptools in a virtualenv, I can get the package to install and be usable only by doing

```bash
python setup.py develop
```

I get:

```bash
C:\Users\Phillip\Desktop\pypackgen (master -> origin)
(pypackgen) λ pypackgener
This should have worked.
```

however, when I perform:

```bash
python setup.py install
```

the Python module is not available, and the scripts don't work saying they can't import the module. 

```bash
C:\Users\Phillip\Desktop\pypackgen (master -> origin)
(pypackgen) λ pypackgener
Traceback (most recent call last):
  File "C:\Users\Phillip\Desktop\pypackgen\venv\pypackgen\Scripts\pypackgener-script.py", line 11, in <module>
    load_entry_point('pypackgen==0.0.1', 'console_scripts', 'pypackgener')()
  File "C:\Users\Phillip\Desktop\pypackgen\venv\pypackgen\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Phillip\Desktop\pypackgen\venv\pypackgen\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\Users\Phillip\Desktop\pypackgen\venv\pypackgen\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Users\Phillip\Desktop\pypackgen\venv\pypackgen\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'pypackgen'
```

Why does this work with `python setup.py develop` but not `python setup.py intsall`? Seems very counter-intuitive.

# References

* https://gist.github.com/predatorian3/9e8e1cbf5f38f69dc3714df7dc2f3810

**Comment by FilBot3** [comment]
in the `setup.py` try setting `package=setuptools.find_package(where='src'),` to see if that works. If not, you'll need to search further.

**Comment by FilBot3** [comment]
Adding the where='src' did the trick. this can be closed now.
